"""create_migration_requests_table

Revision ID: db1e145a8e73
Revises: e24abb6050e6
Create Date: 2026-02-22 19:19:50.519082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1e145a8e73'
down_revision: Union[str, None] = 'e24abb6050e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('account_size', sa.String(length=120), nullable=False),
    sa.Column('mt5_server', sa.String(length=255), nullable=False),
    sa.Column('mt5_account_number', sa.String(length=50), nullable=False),
    sa.Column('mt5_password', sa.String(length=255), nullable=False),
    sa.Column('bank_account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_code', sa.String(length=10), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_amount', sa.Float(), nullable=True),
    sa.Column('transfer_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['admin_allowlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_requests_id'), 'migration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_migration_requests_user_id'), 'migration_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_requests_user_id'), table_name='migration_requests')
    op.drop_index(op.f('ix_migration_requests_id'), table_name='migration_requests')
    op.drop_table('migration_requests')
    # ### end Alembic commands ###
