import dotenv from 'dotenv'

dotenv.config()

export const env = {
  port: Number(process.env.PORT ?? 4000),
  databaseUrl: process.env.DATABASE_URL ?? '',
  nodeEnv: process.env.NODE_ENV ?? 'development',
  supabaseUrl: process.env.SUPABASE_URL ?? '',
  supabaseJwksUrl: process.env.SUPABASE_JWKS_URL ?? '',
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? '',
  appPublicBaseUrl: process.env.APP_PUBLIC_BASE_URL ?? '',
  safehavenBaseUrl: process.env.SAFEHAVEN_BASE_URL ?? 'https://api.sandbox.safehavenmfb.com',
  safehavenClientId: process.env.SAFEHAVEN_CLIENT_ID ?? '',
  safehavenPrivateKey: process.env.SAFEHAVEN_PRIVATE_KEY ?? '',
  safehavenAudience: process.env.SAFEHAVEN_AUDIENCE ?? '',
  safehavenSettlementBankCode: process.env.SAFEHAVEN_SETTLEMENT_BANK_CODE ?? '',
  accessEngineBaseUrl: process.env.ACCESS_ENGINE_BASE_URL ?? 'https://access-engine.placeholder',
  safehavenSettlementAccountNumber: process.env.SAFEHAVEN_SETTLEMENT_ACCOUNT_NUMBER ?? '',
  cryptoBtcAddress: process.env.CRYPTO_BTC_ADDRESS ?? '',
  cryptoEthAddress: process.env.CRYPTO_ETH_ADDRESS ?? '',
  cryptoSolAddress: process.env.CRYPTO_SOL_ADDRESS ?? '',
  cryptoTrxAddress: process.env.CRYPTO_TRX_ADDRESS ?? '',
  ctraderEngineSecret: process.env.CTRADER_ENGINE_SECRET ?? '',
  accessEngineApiKey: process.env.ACCESS_ENGINE_API_KEY ?? '',
  r2AccountId: process.env.R2_ACCOUNT_ID ?? '',
  r2AccessKeyId: process.env.R2_ACCESS_KEY_ID ?? '',
  r2SecretAccessKey: process.env.R2_SECRET_ACCESS_KEY ?? '',
  r2BucketName: process.env.R2_BUCKET_NAME ?? '',
  r2PublicBaseUrl: process.env.R2_PUBLIC_BASE_URL ?? '',
  resendApiKey: process.env.RESEND_API_KEY ?? '',
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? '',
  resendReplyToEmail: process.env.RESEND_REPLY_TO_EMAIL ?? '',
  resendDashboardUrl: process.env.RESEND_DASHBOARD_URL ?? 'https://trader.machefunded.com',
}