export type BankListItem = {
  name: string
  routingKey: string | null
  logoImage: string | null
  bankCode: string
  categoryId: string | null
  nubanCode: string | null
}

export const SAFEHAVEN_BANKS: BankListItem[] = [
  {
    name: 'BANC CORP MICROFINANCE BANK',
    routingKey: '090581',
    logoImage: null,
    bankCode: '090581',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'STERLING BANK',
    routingKey: '000001',
    logoImage: null,
    bankCode: '000001',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'KEYSTONE BANK',
    routingKey: '000002',
    logoImage: null,
    bankCode: '000002',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'FIRST CITY MONUMENT BANK',
    routingKey: '000003',
    logoImage: null,
    bankCode: '000003',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'UNITED BANK FOR AFRICA',
    routingKey: '000004',
    logoImage: null,
    bankCode: '000004',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'JAIZ BANK',
    routingKey: '000006',
    logoImage: null,
    bankCode: '000006',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'FIDELITY BANK',
    routingKey: '000007',
    logoImage: null,
    bankCode: '000007',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'POLARIS BANK',
    routingKey: '000008',
    logoImage: null,
    bankCode: '000008',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'CITI BANK',
    routingKey: '000009',
    logoImage: null,
    bankCode: '000009',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'ECOBANK',
    routingKey: '000010',
    logoImage: null,
    bankCode: '000010',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'UNITY BANK',
    routingKey: '000011',
    logoImage: null,
    bankCode: '000011',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'STANBIC IBTC BANK',
    routingKey: '000012',
    logoImage: null,
    bankCode: '000012',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'GTBANK PLC',
    routingKey: '000013',
    logoImage: null,
    bankCode: '000013',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'ACCESS BANK',
    routingKey: '000014',
    logoImage: null,
    bankCode: '000014',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'ZENITH BANK',
    routingKey: '000015',
    logoImage: null,
    bankCode: '000015',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'FIRST BANK OF NIGERIA',
    routingKey: '000016',
    logoImage: null,
    bankCode: '000016',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'WEMA BANK',
    routingKey: '000017',
    logoImage: null,
    bankCode: '000017',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'UNION BANK',
    routingKey: '000018',
    logoImage: null,
    bankCode: '000018',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'ENTERPRISE BANK',
    routingKey: '000019',
    logoImage: null,
    bankCode: '000019',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'STANDARD CHARTERED BANK',
    routingKey: '000021',
    logoImage: null,
    bankCode: '000021',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'SUNTRUST BANK',
    routingKey: '000022',
    logoImage: null,
    bankCode: '000022',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'PROVIDUS BANK',
    routingKey: '000023',
    logoImage: null,
    bankCode: '000023',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'CORONATION MERCHANT BANK',
    routingKey: '060001',
    logoImage: null,
    bankCode: '060001',
    categoryId: '6',
    nubanCode: null,
  },
  {
    name: 'NPF MICROFINANCE BANK',
    routingKey: '070001',
    logoImage: null,
    bankCode: '070001',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FORTIS MICROFINANCE BANK',
    routingKey: '070002',
    logoImage: null,
    bankCode: '070002',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PAGE MFBANK',
    routingKey: '070008',
    logoImage: null,
    bankCode: '070008',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ASO SAVINGS',
    routingKey: '090001',
    logoImage: null,
    bankCode: '090001',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'JUBILEE LIFE',
    routingKey: '090003',
    logoImage: null,
    bankCode: '090003',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SAFETRUST',
    routingKey: '090006',
    logoImage: null,
    bankCode: '090006',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FIRST TRUST MORTGAGE BANK PLC',
    routingKey: '090107',
    logoImage: null,
    bankCode: '090107',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NEW PRUDENTIAL BANK',
    routingKey: '090108',
    logoImage: null,
    bankCode: '090108',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PAGA',
    routingKey: '100002',
    logoImage: null,
    bankCode: '100002',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'PARKWAY-READYCASH',
    routingKey: '100003',
    logoImage: null,
    bankCode: '100003',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'CELLULANT',
    routingKey: '100005',
    logoImage: null,
    bankCode: '100005',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'ETRANZACT',
    routingKey: '100006',
    logoImage: null,
    bankCode: '100006',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'STANBIC IBTC @EASE WALLET',
    routingKey: '100007',
    logoImage: null,
    bankCode: '100007',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'ECOBANK XPRESS ACCOUNT',
    routingKey: '100008',
    logoImage: null,
    bankCode: '100008',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'GT MOBILE',
    routingKey: '100009',
    logoImage: null,
    bankCode: '100009',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'TEASY MOBILE',
    routingKey: '100010',
    logoImage: null,
    bankCode: '100010',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'KUDA MICROFINANCE BANK',
    routingKey: '090267',
    logoImage: null,
    bankCode: '090267',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'VT NETWORKS',
    routingKey: '100012',
    logoImage: null,
    bankCode: '100012',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'KEGOW(CHAMSMOBILE)',
    routingKey: '100036',
    logoImage: null,
    bankCode: '100036',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'FORTIS MOBILE',
    routingKey: '100016',
    logoImage: null,
    bankCode: '100016',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'HEDONMARK',
    routingKey: '100017',
    logoImage: null,
    bankCode: '100017',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'ZENITH MOBILE',
    routingKey: '100018',
    logoImage: null,
    bankCode: '100018',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'FIDELITY MOBILE',
    routingKey: '100019',
    logoImage: null,
    bankCode: '100019',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'MONEY BOX',
    routingKey: '100020',
    logoImage: null,
    bankCode: '100020',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'EARTHOLEUM',
    routingKey: '100021',
    logoImage: null,
    bankCode: '100021',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'STERLING MOBILE',
    routingKey: '100022',
    logoImage: null,
    bankCode: '100022',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'TAGPAY',
    routingKey: '100023',
    logoImage: null,
    bankCode: '100023',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'IMPERIAL HOMES MORTGAGE BANK',
    routingKey: '100024',
    logoImage: null,
    bankCode: '100024',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'NIP VIRTUAL BANK',
    routingKey: '999999',
    logoImage: null,
    bankCode: '999999',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'FINATRUST MICROFINANCE BANK',
    routingKey: '090111',
    logoImage: null,
    bankCode: '090111',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SEED CAPITAL MICROFINANCE BANK',
    routingKey: '090112',
    logoImage: null,
    bankCode: '090112',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TCF MICROFINANCE BANK',
    routingKey: '090115',
    logoImage: null,
    bankCode: '090115',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EMPIRE TRUST MICROFINANCE BANK',
    routingKey: '090114',
    logoImage: null,
    bankCode: '090114',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MICROVIS MICROFINANCE BANK ',
    routingKey: '090113',
    logoImage: null,
    bankCode: '090113',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AMML MICROFINANCE BANK ',
    routingKey: '090116',
    logoImage: null,
    bankCode: '090116',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BOCTRUST MICROFINANCE BANK LIMITED',
    routingKey: '090117',
    logoImage: null,
    bankCode: '090117',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'WETLAND  MICROFINANCE BANK',
    routingKey: '090120',
    logoImage: null,
    bankCode: '090120',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'IBILE MICROFINANCE BANK',
    routingKey: '090118',
    logoImage: null,
    bankCode: '090118',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'REGENT MICROFINANCE BANK',
    routingKey: '090125',
    logoImage: null,
    bankCode: '090125',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NDIORAH MICROFINANCE BANK',
    routingKey: '090128',
    logoImage: null,
    bankCode: '090128',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BC KASH MICROFINANCE BANK',
    routingKey: '090127',
    logoImage: null,
    bankCode: '090127',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'HASAL MICROFINANCE BANK',
    routingKey: '090121',
    logoImage: null,
    bankCode: '090121',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FBNQUEST MERCHANT BANK',
    routingKey: '060002',
    logoImage: null,
    bankCode: '060002',
    categoryId: '6',
    nubanCode: null,
  },
  {
    name: 'RICHWAY MICROFINANCE BANK',
    routingKey: '090132',
    logoImage: null,
    bankCode: '090132',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PERSONAL TRUST MICROFINANCE BANK',
    routingKey: '090135',
    logoImage: null,
    bankCode: '090135',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MICROCRED MICROFINANCE BANK',
    routingKey: '090136',
    logoImage: null,
    bankCode: '090136',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GOWANS MICROFINANCE BANK',
    routingKey: '090122',
    logoImage: null,
    bankCode: '090122',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'RAND MERCHANT BANK',
    routingKey: '000024',
    logoImage: null,
    bankCode: '000024',
    categoryId: '6',
    nubanCode: null,
  },
  {
    name: 'YES MICROFINANCE BANK',
    routingKey: '090142',
    logoImage: null,
    bankCode: '090142',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SAGAMU MICROFINANCE BANK',
    routingKey: '090140',
    logoImage: null,
    bankCode: '090140',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MONEY TRUST MICROFINANCE BANK',
    routingKey: '090129',
    logoImage: null,
    bankCode: '090129',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'LAGOS BUILDING AND INVESTMENT COMPANY',
    routingKey: '070012',
    logoImage: null,
    bankCode: '070012',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'GATEWAY MORTGAGE BANK',
    routingKey: '070009',
    logoImage: null,
    bankCode: '070009',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'ABBEY MORTGAGE BANK',
    routingKey: '070010',
    logoImage: null,
    bankCode: '070010',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'FIRST GENERATION MORTGAGE BANK',
    routingKey: '070014',
    logoImage: null,
    bankCode: '070014',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'PLATINUM MORTGAGE BANK',
    routingKey: '070013',
    logoImage: null,
    bankCode: '070013',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'INFINITY TRUST MORTGAGE BANK',
    routingKey: '070016',
    logoImage: null,
    bankCode: '070016',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'OHAFIA MICROFINANCE BANK',
    routingKey: '090119',
    logoImage: null,
    bankCode: '090119',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'XSLNCE MICROFINANCE BANK',
    routingKey: '090124',
    logoImage: null,
    bankCode: '090124',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'CONSUMER MICROFINANCE BANK',
    routingKey: '090130',
    logoImage: null,
    bankCode: '090130',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ALLWORKERS MICROFINANCE BANK',
    routingKey: '090131',
    logoImage: null,
    bankCode: '090131',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ACCION MICROFINANCE BANK',
    routingKey: '090134',
    logoImage: null,
    bankCode: '090134',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'VISA MICROFINANCE BANK',
    routingKey: '090139',
    logoImage: null,
    bankCode: '090139',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'CHIKUM MICROFINANCE BANK',
    routingKey: '090141',
    logoImage: null,
    bankCode: '090141',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'APEKS MICROFINANCE BANK',
    routingKey: '090143',
    logoImage: null,
    bankCode: '090143',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'CIT MICROFINANCE BANK',
    routingKey: '090144',
    logoImage: null,
    bankCode: '090144',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FULLRANGE MICROFINANCE BANK',
    routingKey: '090145',
    logoImage: null,
    bankCode: '090145',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FFS MICROFINANCE BANK',
    routingKey: '090153',
    logoImage: null,
    bankCode: '090153',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ADDOSSER MICROFINANCE BANK',
    routingKey: '090160',
    logoImage: null,
    bankCode: '090160',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FIDFUND MICROFINANCE BANK',
    routingKey: '090126',
    logoImage: null,
    bankCode: '090126',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AG MORTGAGE BANK',
    routingKey: '100028',
    logoImage: null,
    bankCode: '100028',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'PECANTRUST MICROFINANCE BANK',
    routingKey: '090137',
    logoImage: null,
    bankCode: '090137',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BOWEN MICROFINANCE BANK',
    routingKey: '090148',
    logoImage: null,
    bankCode: '090148',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FUTO MICROFINANCE BANK',
    routingKey: '090158',
    logoImage: null,
    bankCode: '090158',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'REFUGE MORTGAGE BANK',
    routingKey: '070011',
    logoImage: null,
    bankCode: '070011',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'BRENT MORTGAGE BANK',
    routingKey: '070015',
    logoImage: null,
    bankCode: '070015',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'ROYAL EXCHANGE MICROFINANCE BANK',
    routingKey: '090138',
    logoImage: null,
    bankCode: '090138',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'HACKMAN MICROFINANCE BANK',
    routingKey: '090147',
    logoImage: null,
    bankCode: '090147',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TRIDENT MICROFINANCE BANK',
    routingKey: '090146',
    logoImage: null,
    bankCode: '090146',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'INFINITY MICROFINANCE BANK',
    routingKey: '090157',
    logoImage: null,
    bankCode: '090157',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'CREDIT AFRIQUE MICROFINANCE BANK',
    routingKey: '090159',
    logoImage: null,
    bankCode: '090159',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'E-BARCS MICROFINANCE BANK',
    routingKey: '090156',
    logoImage: null,
    bankCode: '090156',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'VFD MFB',
    routingKey: '090110',
    logoImage: null,
    bankCode: '090110',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ECOMOBILE',
    routingKey: '100030',
    logoImage: null,
    bankCode: '100030',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'INNOVECTIVES KESH',
    routingKey: '100029',
    logoImage: null,
    bankCode: '100029',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'EKONDO MICROFINANCE BANK',
    routingKey: '090097',
    logoImage: null,
    bankCode: '090097',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'VIRTUE MICROFINANCE BANK',
    routingKey: '090150',
    logoImage: null,
    bankCode: '090150',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'IRL MICROFINANCE BANK',
    routingKey: '090149',
    logoImage: null,
    bankCode: '090149',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FCMB MOBILE',
    routingKey: '100031',
    logoImage: null,
    bankCode: '100031',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'MUTUAL TRUST MICROFINANCE BANK',
    routingKey: '090151',
    logoImage: null,
    bankCode: '090151',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'OKPOGA MICROFINANCE BANK',
    routingKey: '090161',
    logoImage: null,
    bankCode: '090161',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NOVA MERCHANT BANK',
    routingKey: '060003',
    logoImage: null,
    bankCode: '060003',
    categoryId: '6',
    nubanCode: null,
  },
  {
    name: 'CEMCS MICROFINANCE BANK',
    routingKey: '090154',
    logoImage: null,
    bankCode: '090154',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'DAYLIGHT MICROFINANCE BANK',
    routingKey: '090167',
    logoImage: null,
    bankCode: '090167',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'HAGGAI MORTGAGE BANK LIMITED',
    routingKey: '070017',
    logoImage: null,
    bankCode: '070017',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'MAINSTREET MICROFINANCE BANK',
    routingKey: '090171',
    logoImage: null,
    bankCode: '090171',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GREENBANK MICROFINANCE BANK',
    routingKey: '090178',
    logoImage: null,
    bankCode: '090178',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FAST MICROFINANCE BANK',
    routingKey: '090179',
    logoImage: null,
    bankCode: '090179',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'LAPO MICROFINANCE BANK',
    routingKey: '090177',
    logoImage: null,
    bankCode: '090177',
    categoryId: '0',
    nubanCode: null,
  },
  {
    name: 'HERITAGE BANK',
    routingKey: '000020',
    logoImage: null,
    bankCode: '000020',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'UNIVERSITY OF NIGERIA, NSUKKA MICROFINANCE BANK',
    routingKey: '090251',
    logoImage: null,
    bankCode: '090251',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PENNYWISE MICROFINANCE BANK ',
    routingKey: '090196',
    logoImage: null,
    bankCode: '090196',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ABU MICROFINANCE BANK ',
    routingKey: '090197',
    logoImage: null,
    bankCode: '090197',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NIRSAL NATIONAL MICROFINANCE BANK',
    routingKey: '090194',
    logoImage: null,
    bankCode: '090194',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BOSAK MICROFINANCE BANK',
    routingKey: '090176',
    logoImage: null,
    bankCode: '090176',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ASTRAPOLARIS MICROFINANCE BANK',
    routingKey: '090172',
    logoImage: null,
    bankCode: '090172',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'QUICKFUND MICROFINANCE BANK',
    routingKey: '090261',
    logoImage: null,
    bankCode: '090261',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ALEKUN MICROFINANCE BANK',
    routingKey: '090259',
    logoImage: null,
    bankCode: '090259',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'RENMONEY MICROFINANCE BANK ',
    routingKey: '090198',
    logoImage: null,
    bankCode: '090198',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'STELLAS MICROFINANCE BANK ',
    routingKey: '090262',
    logoImage: null,
    bankCode: '090262',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NEW DAWN MICROFINANCE BANK',
    routingKey: '090205',
    logoImage: null,
    bankCode: '090205',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ALPHA KAPITAL MICROFINANCE BANK ',
    routingKey: '090169',
    logoImage: null,
    bankCode: '090169',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AUCHI MICROFINANCE BANK ',
    routingKey: '090264',
    logoImage: null,
    bankCode: '090264',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AB MICROFINANCE BANK ',
    routingKey: '090270',
    logoImage: null,
    bankCode: '090270',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NIGERIAN NAVY MICROFINANCE BANK ',
    routingKey: '090263',
    logoImage: null,
    bankCode: '090263',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'IMO STATE MICROFINANCE BANK',
    routingKey: '090258',
    logoImage: null,
    bankCode: '090258',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TRUSTFUND MICROFINANCE BANK ',
    routingKey: '090276',
    logoImage: null,
    bankCode: '090276',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GROOMING MICROFINANCE BANK',
    routingKey: '090195',
    logoImage: null,
    bankCode: '090195',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ABOVE ONLY MICROFINANCE BANK ',
    routingKey: '090260',
    logoImage: null,
    bankCode: '090260',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'OLABISI ONABANJO UNIVERSITY MICROFINANCE ',
    routingKey: '090272',
    logoImage: null,
    bankCode: '090272',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ADEYEMI COLLEGE STAFF MICROFINANCE BANK',
    routingKey: '090268',
    logoImage: null,
    bankCode: '090268',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MEGAPRAISE MICROFINANCE BANK',
    routingKey: '090280',
    logoImage: null,
    bankCode: '090280',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TAJ BANK',
    routingKey: '000026',
    logoImage: null,
    bankCode: '000026',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'ARISE MICROFINANCE BANK',
    routingKey: '090282',
    logoImage: null,
    bankCode: '090282',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PRESTIGE MICROFINANCE BANK',
    routingKey: '090274',
    logoImage: null,
    bankCode: '090274',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GLORY MICROFINANCE BANK',
    routingKey: '090278',
    logoImage: null,
    bankCode: '090278',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BAINES CREDIT MICROFINANCE BANK',
    routingKey: '090188',
    logoImage: null,
    bankCode: '090188',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ACCESS(DIAMOND) BANK',
    routingKey: '000005',
    logoImage: null,
    bankCode: '000005',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'PILLAR MICROFINANCE BANK',
    routingKey: '090289',
    logoImage: null,
    bankCode: '090289',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SAFE HAVEN MICROFINANCE BANK',
    routingKey: '090286',
    logoImage: null,
    bankCode: '090286',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AFEKHAFE MICROFINANCE BANK',
    routingKey: '090292',
    logoImage: null,
    bankCode: '090292',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GLOBUS BANK',
    routingKey: '000027',
    logoImage: null,
    bankCode: '000027',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'FIRST OPTION MICROFINANCE BANK',
    routingKey: '090285',
    logoImage: null,
    bankCode: '090285',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'POLYUNWANA MICROFINANCE BANK',
    routingKey: '090296',
    logoImage: null,
    bankCode: '090296',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'OMIYE MICROFINANCE BANK',
    routingKey: '090295',
    logoImage: null,
    bankCode: '090295',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ASSETMATRIX MICROFINANCE BANK',
    routingKey: '090287',
    logoImage: null,
    bankCode: '090287',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TITAN TRUST BANK',
    routingKey: '000025',
    logoImage: null,
    bankCode: '000025',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'LAVENDER MICROFINANCE BANK',
    routingKey: '090271',
    logoImage: null,
    bankCode: '090271',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FCT MICROFINANCE BANK',
    routingKey: '090290',
    logoImage: null,
    bankCode: '090290',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'IKIRE MICROFINANCE BANK',
    routingKey: '090279',
    logoImage: null,
    bankCode: '090279',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PURPLEMONEY MICROFINANCE BANK',
    routingKey: '090303',
    logoImage: null,
    bankCode: '090303',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ACCESS YELLO & BETA',
    routingKey: '100052',
    logoImage: null,
    bankCode: '100052',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TRUSTBANC J6 MICROFINANCE BANK LIMITED',
    routingKey: '090123',
    logoImage: null,
    bankCode: '090123',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SULSPAP MICROFINANCE BANK',
    routingKey: '090305',
    logoImage: null,
    bankCode: '090305',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ESO-E MICROFINANCE BANK',
    routingKey: '090166',
    logoImage: null,
    bankCode: '090166',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EMERALD MICROFINANCE BANK',
    routingKey: '090273',
    logoImage: null,
    bankCode: '090273',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ACCESS MONEY',
    routingKey: '100013',
    logoImage: null,
    bankCode: '100013',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'ALERT MICROFINANCE BANK',
    routingKey: '090297',
    logoImage: null,
    bankCode: '090297',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BRIGHTWAY MICROFINANCE BANK',
    routingKey: '090308',
    logoImage: null,
    bankCode: '090308',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PALMPAY',
    routingKey: '100033',
    logoImage: null,
    bankCode: '100033',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'SPARKLE',
    routingKey: '090325',
    logoImage: null,
    bankCode: '090325',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BALOGUN GAMBARI MICROFINANCE BANK',
    routingKey: '090326',
    logoImage: null,
    bankCode: '090326',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PATRICKGOLD MICROFINANCE BANK',
    routingKey: '090317',
    logoImage: null,
    bankCode: '090317',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MAYFRESH MORTGAGE BANK',
    routingKey: '070019',
    logoImage: null,
    bankCode: '070019',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'TRUST MICROFINANCE BANK',
    routingKey: '090327',
    logoImage: null,
    bankCode: '090327',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AL-BARAKAH MICROFINANCE BANK',
    routingKey: '090133',
    logoImage: null,
    bankCode: '090133',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EYOWO',
    routingKey: '090328',
    logoImage: null,
    bankCode: '090328',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EVANGEL MICROFINANCE BANK ',
    routingKey: '090304',
    logoImage: null,
    bankCode: '090304',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EVERGREEN MICROFINANCE BANK',
    routingKey: '090332',
    logoImage: null,
    bankCode: '090332',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'OCHE MICROFINANCE BANK',
    routingKey: '090333',
    logoImage: null,
    bankCode: '090333',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NUTURE MICROFINANCE BANK',
    routingKey: '090364',
    logoImage: null,
    bankCode: '090364',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FIRSTMONIE WALLET',
    routingKey: '100014',
    logoImage: null,
    bankCode: '100014',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'NEPTUNE MICROFINANCE BANK',
    routingKey: '090329',
    logoImage: null,
    bankCode: '090329',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'U & C MICROFINANCE BANK',
    routingKey: '090315',
    logoImage: null,
    bankCode: '090315',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'UNAAB MICROFINANCE BANK',
    routingKey: '090331',
    logoImage: null,
    bankCode: '090331',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'IKENNE MICROFINANCE BANK',
    routingKey: '090324',
    logoImage: null,
    bankCode: '090324',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MAYFAIR MICROFINANCE BANK',
    routingKey: '090321',
    logoImage: null,
    bankCode: '090321',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'REPHIDIM MICROFINANCE BANK',
    routingKey: '090322',
    logoImage: null,
    bankCode: '090322',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'KONTAGORA MICROFINANCE BANK',
    routingKey: '090299',
    logoImage: null,
    bankCode: '090299',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'CASHCONNECT MICROFINANCE BANK',
    routingKey: '090360',
    logoImage: null,
    bankCode: '090360',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BIPC MICROFINANCE BANK',
    routingKey: '090336',
    logoImage: null,
    bankCode: '090336',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MOLUSI MICROFINANCE BANK',
    routingKey: '090362',
    logoImage: null,
    bankCode: '090362',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'LEGEND MICROFINANCE BANK',
    routingKey: '090372',
    logoImage: null,
    bankCode: '090372',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SEEDVEST MICROFINANCE BANK',
    routingKey: '090369',
    logoImage: null,
    bankCode: '090369',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EAGLE FLIGHT MICROFINANCE BANK',
    routingKey: '090294',
    logoImage: null,
    bankCode: '090294',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'THINK FINANCE MICROFINANCE BANK',
    routingKey: '090373',
    logoImage: null,
    bankCode: '090373',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FETS',
    routingKey: '100001',
    logoImage: null,
    bankCode: '100001',
    categoryId: '12',
    nubanCode: null,
  },
  {
    name: 'COASTLINE MICROFINANCE BANK',
    routingKey: '090374',
    logoImage: null,
    bankCode: '090374',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MINT-FINEX MFB',
    routingKey: '090281',
    logoImage: null,
    bankCode: '090281',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'HEADWAY MICROFINANCE BANK',
    routingKey: '090363',
    logoImage: null,
    bankCode: '090363',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ISALEOYO MICROFINANCE BANK',
    routingKey: '090377',
    logoImage: null,
    bankCode: '090377',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NEW GOLDEN PASTURES MICROFINANCE BANK',
    routingKey: '090378',
    logoImage: null,
    bankCode: '090378',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FSDH',
    routingKey: '400001',
    logoImage: null,
    bankCode: '400001',
    categoryId: '4',
    nubanCode: null,
  },
  {
    name: 'CORESTEP MICROFINANCE BANK',
    routingKey: '090365',
    logoImage: null,
    bankCode: '090365',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FEDPOLY NASARAWA MICROFINANCE BANK',
    routingKey: '090298',
    logoImage: null,
    bankCode: '090298',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FIRMUS MICROFINANCE BANK',
    routingKey: '090366',
    logoImage: null,
    bankCode: '090366',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MANNY MICROFINANCE BANK',
    routingKey: '090383',
    logoImage: null,
    bankCode: '090383',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'DAVODANI  MICROFINANCE BANK',
    routingKey: '090391',
    logoImage: null,
    bankCode: '090391',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EK-RELIABLE MICROFINANCE BANK',
    routingKey: '090389',
    logoImage: null,
    bankCode: '090389',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GTI MICROFINANCE BANK',
    routingKey: '090385',
    logoImage: null,
    bankCode: '090385',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'YOBE MICROFINANCE  BANK',
    routingKey: '090252',
    logoImage: null,
    bankCode: '090252',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: '9 PAYMENT SOLUTIONS BANK',
    routingKey: '120001',
    logoImage: null,
    bankCode: '120001',
    categoryId: '12',
    nubanCode: null,
  },
  {
    name: 'OPAY',
    routingKey: '100004',
    logoImage: null,
    bankCode: '100004',
    categoryId: '12',
    nubanCode: null,
  },
  {
    name: 'VENTURE GARDEN NIGERIA LIMITED',
    routingKey: '110009',
    logoImage: null,
    bankCode: '110009',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'RUBIES MICROFINANCE BANK',
    routingKey: '090175',
    logoImage: null,
    bankCode: '090175',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MOZFIN MICROFINANCE BANK',
    routingKey: '090392',
    logoImage: null,
    bankCode: '090392',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'INTERLAND MICROFINANCE BANK',
    routingKey: '090386',
    logoImage: null,
    bankCode: '090386',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FINCA MICROFINANCE BANK',
    routingKey: '090400',
    logoImage: null,
    bankCode: '090400',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'KONGAPAY',
    routingKey: '100025',
    logoImage: null,
    bankCode: '100025',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'ILISAN MICROFINANCE BANK',
    routingKey: '090370',
    logoImage: null,
    bankCode: '090370',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NWANNEGADI MICROFINANCE BANK',
    routingKey: '090399',
    logoImage: null,
    bankCode: '090399',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GIREI MICROFINANACE BANK',
    routingKey: '090186',
    logoImage: null,
    bankCode: '090186',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'OSCOTECH MICROFINANCE BANK',
    routingKey: '090396',
    logoImage: null,
    bankCode: '090396',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BRIDGEWAY MICROFINANACE BANK',
    routingKey: '090393',
    logoImage: null,
    bankCode: '090393',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'KREDI MONEY MICROFINANCE BANK ',
    routingKey: '090380',
    logoImage: null,
    bankCode: '090380',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SHERPERD TRUST MICROFINANCE BANK',
    routingKey: '090401',
    logoImage: null,
    bankCode: '090401',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'NOWNOW DIGITAL SYSTEMS LIMITED',
    routingKey: '100032',
    logoImage: null,
    bankCode: '100032',
    categoryId: '0',
    nubanCode: null,
  },
  {
    name: 'AMAC MICROFINANCE BANK',
    routingKey: '090394',
    logoImage: null,
    bankCode: '090394',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'LIVINGTRUST MORTGAGE BANK PLC',
    routingKey: '070007',
    logoImage: null,
    bankCode: '070007',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'M36',
    routingKey: '100035',
    logoImage: null,
    bankCode: '100035',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'NNEW WOMEN MICROFINANCE BANK ',
    routingKey: '090283',
    logoImage: null,
    bankCode: '090283',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GMB MICROFINANCE BANK',
    routingKey: '090408',
    logoImage: null,
    bankCode: '090408',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: '3LINE CARD MANAGEMENT LIMITED',
    routingKey: '110005',
    logoImage: null,
    bankCode: '110005',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'TEAMAPT LIMITED',
    routingKey: '110007',
    logoImage: null,
    bankCode: '110007',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'INTERSWITCH LIMITED',
    routingKey: '110003',
    logoImage: null,
    bankCode: '110003',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'PAYSTACK PAYMENT LIMITED',
    routingKey: '110006',
    logoImage: null,
    bankCode: '110006',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'TRUSTBOND MORTGAGE BANK',
    routingKey: '090005',
    logoImage: null,
    bankCode: '090005',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'NAGARTA MICROFINANCE BANK',
    routingKey: '090152',
    logoImage: null,
    bankCode: '090152',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ADVANS LA FAYETTE  MICROFINANCE BANK',
    routingKey: '090155',
    logoImage: null,
    bankCode: '090155',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'STANFORD MICROFINANCE BANK',
    routingKey: '090162',
    logoImage: null,
    bankCode: '090162',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FIRST ROYAL MICROFINANCE BANK',
    routingKey: '090164',
    logoImage: null,
    bankCode: '090164',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PETRA MICROFINANCE BANK',
    routingKey: '090165',
    logoImage: null,
    bankCode: '090165',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GASHUA MICROFINANCE BANK',
    routingKey: '090168',
    logoImage: null,
    bankCode: '090168',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'RELIANCE MICROFINANCE BANK',
    routingKey: '090173',
    logoImage: null,
    bankCode: '090173',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MALACHY MICROFINANCE BANK',
    routingKey: '090174',
    logoImage: null,
    bankCode: '090174',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AMJU UNIQUE MICROFINANCE BANK',
    routingKey: '090180',
    logoImage: null,
    bankCode: '090180',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ESAN MICROFINANCE BANK',
    routingKey: '090189',
    logoImage: null,
    bankCode: '090189',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MUTUAL BENEFITS MICROFINANCE BANK',
    routingKey: '090190',
    logoImage: null,
    bankCode: '090190',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'KCMB MICROFINANCE BANK',
    routingKey: '090191',
    logoImage: null,
    bankCode: '090191',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MIDLAND MICROFINANCE BANK',
    routingKey: '090192',
    logoImage: null,
    bankCode: '090192',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'UNICAL MICROFINANCE BANK',
    routingKey: '090193',
    logoImage: null,
    bankCode: '090193',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'LOVONUS MICROFINANCE BANK',
    routingKey: '090265',
    logoImage: null,
    bankCode: '090265',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'UNIBEN MICROFINANCE BANK',
    routingKey: '090266',
    logoImage: null,
    bankCode: '090266',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GREENVILLE MICROFINANCE BANK',
    routingKey: '090269',
    logoImage: null,
    bankCode: '090269',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AL-HAYAT MICROFINANCE BANK',
    routingKey: '090277',
    logoImage: null,
    bankCode: '090277',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BRETHREN MICROFINANCE BANK',
    routingKey: '090293',
    logoImage: null,
    bankCode: '090293',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'EDFIN MICROFINANCE BANK',
    routingKey: '090310',
    logoImage: null,
    bankCode: '090310',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK',
    routingKey: '090318',
    logoImage: null,
    bankCode: '090318',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'KADPOLY MICROFINANCE BANK',
    routingKey: '090320',
    logoImage: null,
    bankCode: '090320',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MAINLAND MICROFINANCE BANK',
    routingKey: '090323',
    logoImage: null,
    bankCode: '090323',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'APPLE MICROFINANCE BANK',
    routingKey: '090376',
    logoImage: null,
    bankCode: '090376',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BORGU  MICROFINANCE BANK',
    routingKey: '090395',
    logoImage: null,
    bankCode: '090395',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK',
    routingKey: '090398',
    logoImage: null,
    bankCode: '090398',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'OLOWOLAGBA MICROFINANCE BANK',
    routingKey: '090404',
    logoImage: null,
    bankCode: '090404',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'BUSINESS SUPPORT MICROFINANCE BANK',
    routingKey: '090406',
    logoImage: null,
    bankCode: '090406',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MKUDI',
    routingKey: '100011',
    logoImage: null,
    bankCode: '100011',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'INTELLIFIN',
    routingKey: '100027',
    logoImage: null,
    bankCode: '100027',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'PAYATTITUDE ONLINE',
    routingKey: '110001',
    logoImage: null,
    bankCode: '110001',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED',
    routingKey: '110002',
    logoImage: null,
    bankCode: '110002',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'FIRST APPLE LIMITED',
    routingKey: '110004',
    logoImage: null,
    bankCode: '110004',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'CYBERSPACE LIMITED',
    routingKey: '110014',
    logoImage: null,
    bankCode: '110014',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'ACCELEREX NETWORK LIMITED',
    routingKey: '090202',
    logoImage: null,
    bankCode: '090202',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'HOPEPSB',
    routingKey: '120002',
    logoImage: null,
    bankCode: '120002',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'BAYERO UNIVERSITY MICROFINANCE BANK',
    routingKey: '090316',
    logoImage: null,
    bankCode: '090316',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'MARITIME MICROFINANCE BANK',
    routingKey: '090410',
    logoImage: null,
    bankCode: '090410',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'AGOSASA MICROFINANCE BANK',
    routingKey: '090371',
    logoImage: null,
    bankCode: '090371',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ZENITH EASY WALLET',
    routingKey: '100034',
    logoImage: null,
    bankCode: '100034',
    categoryId: '10',
    nubanCode: null,
  },
  {
    name: 'COOP MORTGAGE BANK',
    routingKey: '070021',
    logoImage: null,
    bankCode: '070021',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'CARBON',
    routingKey: '100026',
    logoImage: null,
    bankCode: '100026',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'LINKS MICROFINANCE BANK',
    routingKey: '090435',
    logoImage: null,
    bankCode: '090435',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'RIGO MICROFINANCE BANK',
    routingKey: '090433',
    logoImage: null,
    bankCode: '090433',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PEACE MICROFINANCE BANK',
    routingKey: '090402',
    logoImage: null,
    bankCode: '090402',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SPECTRUM MICROFINANCE BANK ',
    routingKey: '090436',
    logoImage: null,
    bankCode: '090436',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'GREENWICH MERCHANT BANK',
    routingKey: '060004',
    logoImage: null,
    bankCode: '060004',
    categoryId: '6',
    nubanCode: null,
  },
  {
    name: 'LOTUS BANK',
    routingKey: '000029',
    logoImage: null,
    bankCode: '000029',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'TANGERINE MONEY',
    routingKey: '090426',
    logoImage: null,
    bankCode: '090426',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PARALLEX BANK',
    routingKey: '000030',
    logoImage: null,
    bankCode: '000030',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'SAFEGATE MICROFINANCE BANK',
    routingKey: '090485',
    logoImage: null,
    bankCode: '090485',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'YCT MICROFINANCE BANK',
    routingKey: '090466',
    logoImage: null,
    bankCode: '090466',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SUPPORT MICROFINANCE BANK',
    routingKey: '090446',
    logoImage: null,
    bankCode: '090446',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'CBN',
    routingKey: '000028',
    logoImage: null,
    bankCode: '000028',
    categoryId: '11',
    nubanCode: null,
  },
  {
    name: 'FEDETH MICROFINANCE BANK',
    routingKey: '090482',
    logoImage: null,
    bankCode: '090482',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'DOT MICROFINANCE BANK',
    routingKey: '090470',
    logoImage: null,
    bankCode: '090470',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'ZIKORA MICROFINANCE BANK',
    routingKey: '090504',
    logoImage: null,
    bankCode: '090504',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'SOLID ALLIANZE MICROFINANCE BANK',
    routingKey: '090506',
    logoImage: null,
    bankCode: '090506',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'PREMIUM TRUST  BANK',
    routingKey: '000031',
    logoImage: null,
    bankCode: '000031',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'SMARTCASH PAYMENT SERVICE BANK',
    routingKey: '120004',
    logoImage: null,
    bankCode: '120004',
    categoryId: '0',
    nubanCode: null,
  },
  {
    name: 'MONIEPOINT MICROFINANCE BANK',
    routingKey: '090405',
    logoImage: null,
    bankCode: '090405',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'HOMEBASE MORTGAGE BANK',
    routingKey: '0070024',
    logoImage: null,
    bankCode: '0070024',
    categoryId: '7',
    nubanCode: null,
  },
  {
    name: 'MOMO PAYMENT SERVICE BANK ',
    routingKey: '120003 ',
    logoImage: null,
    bankCode: '120003 ',
    categoryId: '12',
    nubanCode: null,
  },
  {
    name: 'GOODNEWS MICROFINANCE BANK',
    routingKey: '090495',
    logoImage: null,
    bankCode: '090495',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'FEWCHORE FINANCE COMPANY LIMITED',
    routingKey: '050002',
    logoImage: null,
    bankCode: '050002',
    categoryId: '5',
    nubanCode: null,
  },
  {
    name: 'COVENANT MICROFINANCE BANK',
    routingKey: '070006',
    logoImage: null,
    bankCode: '070006',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'STATESIDE MFB',
    routingKey: '090583',
    logoImage: null,
    bankCode: '090583',
    categoryId: '9',
    nubanCode: null,
  },
  {
    name: 'TEST BANK',
    routingKey: '999239',
    logoImage: null,
    bankCode: '999239',
    categoryId: '2',
    nubanCode: null,
  },
  {
    name: 'SAFE HAVEN SANDBOX BANK',
    routingKey: '999240',
    logoImage: null,
    bankCode: '999240',
    categoryId: '9',
    nubanCode: null,
  },
]